# shared constants

ACCOUNT_TYPES = ("ASSET", "LIABILITY", "EQUITY", "INCOME", "EXPENSE")
NORMAL_BALANCE = {
    "ASSET": "DEBIT", "EXPENSE": "DEBIT",
    "LIABILITY": "CREDIT", "EQUITY": "CREDIT", "INCOME": "CREDIT",
}
CASH_FLOW_CATEGORIES = ("CASH", "OPERATING", "INVESTING", "FINANCING", "NONCASH")
ENTRY_TYPES = ("GENERAL", "ADJUSTING", "CLOSING", "REVERSING", "OPENING")
BUSINESS_TYPES = ("Service", "Merchandising/Trading", "Manufacturing")
ORG_TYPES = ("Sole Proprietorship", "Partnership", "Corporation")
INVENTORY_SYSTEMS = ("PERIODIC", "PERPETUAL")

CASH = "1000"
INCOME_SUMMARY = "3999"
RETAINED_EARNINGS = "3900"